spring:
  config:
    activate:
      on-profile: develop
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/jober;
    username: sa
    password: 1234