spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://15.164.102.187:3306/jober
      ?useUnicode=true
      &characterEncoding=utf8
      &useSSL=false
      &allowPublicKeyRetrieval=true
    username: server
    password: joberteam1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN     # CookieCsrfTokenRepository의 기본 쿠키명
      header-name: X-XSRF-TOKEN

logging:
  config: classpath:log4j2-production.yml
  level:
    org.springframework.security: INFO
    com.movement.mvp: INFO
    org.springframework.web.multipart: INFO

# AI Flask 서버 설정
ai:
  flask:
    base-url: http://15.164.102.187:8000  # AI Flask 서버 URL (추후 실제 URL로 변경)
    chat-endpoint: /api/chat  # AI 채팅 API 엔드포인트

security:
  permit-all:
    - /swagger-ui/**
    - /v3/api-docs/**
    - /h2-console/**
    - /swagger-ui.html
    - /admin/sessions/**
  permit-post-user:
    - /user/register
    - /user/login
    - /user/id/check
    - /user/email/check