spring:
  application:
    name: jober-server
  profiles:
    active: develop

  mail:
    host: smtp.gmail.com
    port: 587
    username: ndh3042@gmail.com
    password: sbyzimcfeyzhwbvs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: "no-reply@your-domain.com"
  reset:
    url: "https://www.jober-1team.com/reset-password/"

server:
  port: 8080
