spring:
  config:
    activate:
      on-profile: develop
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/jober;
    username: sa
    password: 1234

springdoc:
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN     # CookieCsrfTokenRepository의 기본 쿠키명
      header-name: X-XSRF-TOKEN
  api-docs:
    enabled: true

logging:
  config: classpath:log4j2-develop.yml
  level:
    org.springframework.security: DEBUG
    com.movement.mvp: DEBUG
    org.springframework.web.multipart: DEBUG

# AI Flask 서버 설정
ai:
  flask:
    base-url: http://13.209.3.58:8000  # AI Flask 서버 URL (추후 실제 URL로 변경)
    chat-endpoint: /api/chat  # AI 채팅 API 엔드포인트

security:
  permit-all:
    - /actuator/health
    - /swagger-ui/**
    - /v3/api-docs/**
    - /auth/**
    - /h2-console/**
    - /admin/sessions/**
  permit-user:
    - /user/register
    - /user/login
    - /user/id/check
    - /user/email/check
    - /user/password
    - /user/token/check