name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - develop
      - release/**

permissions:
  contents: read
  packages: write
  security-events: write
  checks: write
  pull-requests: write

jobs:
  spotless-check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: Final-1team-BE

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        working-directory: Final-1team-BE
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: spotless-check
    strategy:
      matrix:
        java-version: ["21"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: Final-1team-BE

      - name: Run Gradle Build
        run: ./gradlew build -x test
        working-directory: Final-1team-BE

      - name: Run Tests
        run: ./gradlew test
        working-directory: Final-1team-BE

      - name: Upload build artifacts
        if: matrix.java-version == '21' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: mvp/build/libs/

  security-scan:
    na
