      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail

            mkdir -p ~/app/docker/production
            cd ~/app/docker/production

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 빌드와 동일하게 github.ref_name을 태그로 사용
            TAG="${{ github.ref_name }}"
            export REPO_LC="${{ env.REPO_LC }}"
            export TAG="$TAG"

            IMAGE="ghcr.io/${{ env.REPO_LC }}/user-service:${TAG}"
            echo "Deploying IMAGE=${IMAGE}"

            docker pull "$IMAGE" || { echo "manifest not found: $IMAGE"; exit 1; }

            docker compose -f docker-compose.yml down --remove-orphans || true
            docker compose -f docker-compose.yml up -d --pull always --wait || \
              docker compose -f docker-compose.yml up -d --pull always

            sleep 5
            docker compose -f docker-compose.yml ps
            docker compose -f docker-compose.yml logs --tail=200

            docker image prune -f
